name: Setup Repo
description: Prepare repo

inputs:
  submodules:
    description: Clone submodules
    default: false # this is string

runs:
  using: composite
  steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: ${{ inputs.skip-expo == 'true' }}
      - name: setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'
      - run: corepack enable
        shell: bash
      - run: pnpm --version
        shell: bash
      - run: pnpm i
        shell: bash
