name: Setup Repo
description: Prepare repo

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
    - name: setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: pnpm
        registry-url: 'https://registry.npmjs.org'
    - run: pnpm i --frozen-lockfile
      shell: bash
