name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  packages:
    name: check npm install
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - name: check npm ci
        run: npm ci
  lint:
    name: run lint
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - name: npm ci
        run: npm ci
      - name: run lint
        run: npm run lint -- --max-warnings=0
  format:
    name: run format
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - name: npm ci
        run: npm ci
      - name: run format
        run: npx prettier --check .
  type-check:
    name: run type-check
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - name: npm ci
        run: npm ci
      - name: run type-check
        run: npm run type-check
  build:
    name: run build
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: 3.1.1
      - run: sudo apt install -y autotools-dev autoconf libtool pkg-config
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - name: npm ci
        run: npm ci
      - name: run build
        run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: wasm-dist
          path: |
            ./wasm-out/*
            !./wasm-out/speex.d.ts
  test:
    name: run test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - name: npm ci
        run: npm ci
      - uses: actions/download-artifact@v2
        with:
          name: wasm-dist
          path: ./wasm-out-
      - run: |
          mv ./wasm-out-/* ./wasm-out/
          rm -r ./wasm-out-
      - name: run test
        run: npm run test
