name: automatic release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-repo
        with:
          submodules: true
      - uses: mymindstorm/setup-emsdk@v12
        with:
          version: 3.1.32
      - run: sudo apt install -y autotools-dev autoconf libtool pkg-config
      - name: build
        run: pnpm run build
      - name: release
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
