name: automatic release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: release
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/setup-repo
      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.56
      - run: sudo apt install -y autotools-dev autoconf libtool pkg-config
      - name: build
        run: pnpm run build
      - name: release
        run: pnpm publish --access public --no-git-checks --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
